// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOcJ9Up8DTzdRAg_V4MXIZaj-aTsI9t-c',
    appId: '1:688490305856:android:b4a4704379985e66cd82a5',
    messagingSenderId: '688490305856',
    projectId: 'tarumt-carpooling-c71c7',
    databaseURL: 'https://tarumt-carpooling-c71c7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tarumt-carpooling-c71c7.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxV-JpyGVw4WvlX1qOij1IQG3sAyO1onk',
    appId: '1:688490305856:web:7dfaec94708c867acd82a5',
    messagingSenderId: '688490305856',
    projectId: 'tarumt-carpooling-c71c7',
    authDomain: 'tarumt-carpooling-c71c7.firebaseapp.com',
    databaseURL: 'https://tarumt-carpooling-c71c7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tarumt-carpooling-c71c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmPRYXLhduWhRMCxm7QBZW8OBBALd4A1Y',
    appId: '1:688490305856:ios:a47ba4b0554e7cffcd82a5',
    messagingSenderId: '688490305856',
    projectId: 'tarumt-carpooling-c71c7',
    databaseURL: 'https://tarumt-carpooling-c71c7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tarumt-carpooling-c71c7.firebasestorage.app',
    iosBundleId: 'com.tarumt.tarumtCarpool',
  );

}